// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rater_api.Data;

#nullable disable

namespace rater_api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220307003801_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("rater_api.Models.SchoolProgram", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SchoolPrograms");

                    b.HasData(
                        new
                        {
                            Id = "qwiqwlkht",
                            ProgramDesc = "This is the program for web full stack",
                            ProgramName = "Full Stack Web Development"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
