// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rater_api.Data;

#nullable disable

namespace rater_api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220314072051_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("rater_api.Models.ProgramRate", b =>
                {
                    b.Property<int>("ProgramRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramReview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RateNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchoolProgramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProgramRateId");

                    b.HasIndex("SchoolProgramId");

                    b.ToTable("ProgramRate");

                    b.HasData(
                        new
                        {
                            ProgramRateId = 1,
                            Created_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramReview = "FSWD sucks",
                            RateNumber = 1,
                            SchoolProgramId = 1
                        });
                });

            modelBuilder.Entity("rater_api.Models.SchoolProgram", b =>
                {
                    b.Property<int>("SchoolProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SchoolProgramId");

                    b.ToTable("SchoolProgram");

                    b.HasData(
                        new
                        {
                            SchoolProgramId = 1,
                            ProgramDesc = "This is FSWD",
                            ProgramName = "FSWD"
                        });
                });

            modelBuilder.Entity("rater_api.Models.ProgramRate", b =>
                {
                    b.HasOne("rater_api.Models.SchoolProgram", null)
                        .WithMany("ProgramRates")
                        .HasForeignKey("SchoolProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("rater_api.Models.SchoolProgram", b =>
                {
                    b.Navigation("ProgramRates");
                });
#pragma warning restore 612, 618
        }
    }
}
